name: secure_auth
description: CET324-Advanced Cyber Sercurity assignmnet. This application illustrates appropriate design approaches to cybersercurity in applications.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

# Version number and build number for this application
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

# Packages the application needs
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^1.15.0
  firebase_auth: ^3.3.15
  cloud_firestore: ^3.1.13
  shared_preferences: ^2.0.13
  http: ^0.13.4
  g_recaptcha_v3: ^0.0.4
  encrypt: ^5.0.1
  crypto: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
